# Parameters for local training
test_size: 0.25
batch_size: 32
epochs: 1
# trained layers 0 means all layers in the model, otherwise just select the layers based on the identified number
trained_Layers: 1