  version: '3.3'
  services:
    client:
      environment:
        - GET_HOSTS_FROM=dns
      image: "nlp-imdb:latest"
      build:
        context: .
      working_dir: /app
      command: /bin/bash -c "fedn run client -in client.yaml"
      volumes:
        - ./data/clients/1:/app/data
        - ./client.yaml:/app/client.yaml